### PR TITLE
Adding registered types and field type mappings to command line options

### PR DESCRIPTION
**Pull request by ryanburst**
Adds the following command line options:

--register-types=type1:value,type2:value
--type-map=type1:value,type2:value

This allows the user to specify additional doctrine types to register as well as convert additional field types.

### CODE REVIEW

**Comment by barryvdh** [comment]
Wouldn't it be easier to make this configurable via a config file, instead of commandline options?

**Comment by ryanburst** [comment]
Absolutely. Do you me to create a separate PR or push updates to this branch?

**Comment by barryvdh** [comment]
Just push to this branch If you want. And maybe add your bit thing to the defaults?

**Comment by ryanburst** [comment]
Can do. Do you prefer the $app['config'] version and pushing it through the constructor, or the \Config::get version right in the MigrationGeneratorCommand constructor?

**Comment by ryanburst** [comment]
Also, would you prefer a user config overrides the default options or merges them (the difference between putting the defaults into a default config vs a property)

**Comment by barryvdh** [comment]
$app['config'] version, or just pass 2 arrays to the constructor (and use $app['config'] in the serviceprovider to create the 2 arrays).
And just put the options in the config, so the user can override them just the way they like.

**Comment by ryanburst** [comment]
Alright, I added a config folder for defaults and pull in config options in service provider which gets passed into the constructor and set. The main class sets the config options based on existing properties. This should make it easier to integrate any other configuration options. 

User's can provide their own configurations via the normal Laravel way (app/config/packages/barryvdh/laravel-migration-generator/environment/config.php).

**Comment by barryvdh** [comment]
Cool thanks :)
Looks good, haven't got time to test this properly, but I'll trust you on this ;)

**Comment by ryanburst** [comment]
Awesome, thanks. Drop me a line if something comes up.

**Pull request merged**
